# Generated by Django 5.0.3 on 2024-06-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denounces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='enviada',
            field=models.CharField(default='não', max_length=3),
        ),
    ]
